// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'src/filtered_list_test.dart' as src_filtered_list_test;

void main() {
  src_filtered_list_test.main();
}
