name: Publish

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:dev

    steps:
    # Without this, there are no files in the directory.
    - uses: actions/checkout@v2

    # getting for branch name
    - uses: nelonoel/branch-name@v1.0.1

    - name: Set version name
      run: echo "VERSION_NAME=$(echo $BRANCH_NAME | cut -d '/' -f 2)" >> $GITHUB_ENV

    # delete unnecessary directories
    - run: |
        rm -rf ./test
        rm -rf ./tool

    - name: Print Dart SDK version
      run: dart --version

    - name: Install dependencies
      run: dart pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: dart analyze

    - name: Run tests
      run: dart test

    # tagging version
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "$VERSION_NAME"
        git tag "$VERSION_NAME"
        git push origin "$VERSION_NAME"

    # publish to pub.dev
    - name: publish
      uses: sakebook/actions-flutter-pub-publisher@v1.3.1
      with:
        credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
        flutter_package: true
        skip_test: true
        dry_run: false
